version: '3'
services:
  impala:
    image: codingtony/impala:latest
    container_name: impala
    ports:
      - 9000:9000
      - 50010:50010
      - 50020:50020
      - 50070:50070
      - 50075:50075
      - 21000:21000
      - 21050:21050
      - 25000:25000
      - 25010:25010
      - 25020:25020
    volumes:
      - /home/srv/dockerimpala/sql:/mnt
      - /home/srv/dockerimpala/data:/data/impala